### ISSUE TITLE
Merge Page & Ayah Bookmarks

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#103]
**From collin,**
- I'm not sure why the page bookmarks and ayah bookmarks actually need separate sections, since they function the same way from the user's perspective. 
- They certainly don't need to show their headers when they're empty.

**Comment by mohamede1945** [comment]
Need other opinions and see which one is the best to go.

**Comment by abunur** [comment]
Agree they should be merged.  Also, for ayah bookmarks the UI needs to show the ayah number next to the bookmark.

**Comment by mohamede1945** [comment]
Oh! We had it and I removed it while adding time ago. That's definitely should come back.

**Comment by Abdullah076** [comment]
i think different bookmarks are fine. as it makes it easier for people who takes a lot of bookmarks

**Comment by mohamede1945** [comment]
We have bookmarks & Notes as different sections. There's no concept of ayah bookmark anymore.
