### ISSUE TITLE
A lighter black color for Reading View

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#107]
**From collin,**
The black-on-white colour scheme in the reading views is kind of harsh, could use some variety

**Comment by ahmedre** [comment]
on Android, we have an option to tweak the gray level of the font

**Comment by abdelouali** [comment]
I think, use better a gray color: #3c3c3d; looks clean this one.

**Comment by mohamede1945** [comment]
@ahmedre https://github.com/quran/quran-ios/issues/108 I think something like iBook should be good. I didn't have a look at how the Android app is doing it, I will look at it too inshaa'Allah

**Comment by mohamede1945** [comment]
@abdelouali Thank you for the suggestion. I think I would go with something like that.
