### ISSUE TITLE
Quran Scrolls back to First Page 

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#114]
Steps to reproduce, I can reproduce it consistently on iPhone 6.

1. Open any page in the middle of the Quran (e.g. page#50).
2. Rotate the device to Landscape.
3. Lock the device while still in Landscape.
4. Rotate the device back to portrait while the device is locked.
5. Unlock the device while it is in Portrait.
6. You should see the first page instead of page#50.

**Comment by abunur** [comment]
May be related to #133 - see comment about bookmarks as well

**Comment by mohamede1945** [comment]
Can be reproduced using Multitasking on iPad
https://youtu.be/cZXaTWcg_A4

**Comment by mohamede1945** [comment]
Fixed
