### ISSUE TITLE
Enable/Disable auto scroll

### ISSUE THREAD

**Issue by jayhub** [quran/quran-ios#118]
When user taps a verse start audio playback from that point onwards. This probably means that user will have to download the audio files first.

**Comment by mohamede1945** [comment]
But why would the user reads the Quran on a page and listen to a totally different page?

**Comment by jayhub** [comment]
I think it will give user the freedom to scroll up to finish reading a translation that they missed by few words.

**Comment by mohamede1945** [comment]
I still don't see a user who will do 2 different things, listening to Arabic Quran and reading translation! 

Or even if he is listening to Ibrahim Walk (English translation) and reading the same translation, that means user shouldn't miss anything.

**Comment by jayhub** [comment]
Yes you are right so I disregarded that feature and changed it to another feature request.

**Comment by mohamede1945** [comment]
Ok. And really thank you for testing the app and provide feedback. 

JazkaAllah khiran

**Comment by jayhub** [comment]
No problem brother. Inshallah I will be using this app on a regular basis specially during ramadan. So inshallah you will be getting sawab for that.

**Comment by mohamede1945** [comment]
Thank you for reporting this new issue, but instead of editing this issue, can you create a new one, so that we don't lose history. 

JazkaAllah khiran

**Comment by jayhub** [comment]
Sure will do.

**Comment by mohamede1945** [comment]
Will close it, as we agreed
