### ISSUE TITLE
V1 Screens Localization

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#12]
- [ ] Add localization for new labels not in the Android app.
- [ ] Make sure all languages supported by Android app is supported in iOS.

**Comment by abdelouali** [comment]
Salam mohamed, can i work on the language thing without my macbook? With my windows pc? It is xml or not?

**Comment by mohamede1945** [comment]
Salam Abdelouali,
Yes, you can. They are .strings file. You can find folders inside with ".lproj" as suffix to the directory name. For example this folder https://github.com/quran/quran-ios/tree/master/Quran/ar.lproj

That folder https://github.com/quran/quran-ios/tree/master/Quran/Base.lproj is the English one and has correct values, you can translate other folders and take that folder "Base.lproj" as the reference to you for English translation.

**Comment by abdelouali** [comment]
Salam Mohamed, 

thank you for the info. I will work this night on this.

Shokran

**Comment by mohamede1945** [comment]
Implemented!
