### ISSUE TITLE
Add ability to add a note for a Bookmark

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#120]

**Comment by ahmedre** [comment]
let's sync up before doing this to make sure we do something consistent between iOS and Android

**Comment by mohamede1945** [comment]
Sure. I got it from an app store comment.

**Comment by abunur** [comment]
Related to #150 ; notes should be linked / same as bookmarks and should be synchronized between devices via iCloud

**Comment by mohamede1945** [comment]
Sounds good

**Comment by mohamede1945** [comment]
Fixed and live.
