### ISSUE TITLE
how create ayahinfo_1280.db and images

### ISSUE THREAD

**Issue by dajdouj10** [quran/quran-ios#146]
how create ayahinfo_1280.db and images for other type mashef

**Comment by mohamede1945** [comment]
Sorry, didn't understand your question.

**Comment by dajdouj10** [comment]
how can we use ayah-detection to generate ayahinfo.db for mashef el madina (مصحف المدينة ) pages.
Hope your nice help.

**Comment by mohamede1945** [comment]
Personally, I don't know details. But from outside, I understand it's done in https://github.com/quran/quran.com-images

**Comment by mohamede1945** [comment]
Closing, please feel free to reopen if you want more information.
