### ISSUE TITLE
Issue when running project

### ISSUE THREAD

**Issue by ahhmad** [quran/quran-ios#149]
Binary operator '+' cannot be applied to operands of type '[QariAudioFile]' and '[QariDatabaseAudioFile]'

**Comment by mohamede1945** [comment]
Which version of xcode did you use?

**Comment by ahhmad** [comment]
Version 8.2.1

**Comment by mohamede1945** [comment]
It is probably swift version difference you have Swift 3.0.2 while I'm using Swift 3.1.1 (xcode 8.3.2). I cannot confirm it until  I try to test it with xcode 8.2.1 and see.

**Comment by mohamede1945** [comment]
[Now I can confirm it is a swift version difference problem](https://travis-ci.org/mohamede1945/quran-ios/jobs/231845568). Upgrading to Swift 3.1.1 (Xcode 8.3.x) should resolve the problem.

**Comment by mohamede1945** [comment]
I should update the toolchain in the readme.
