### ISSUE TITLE
Feature Request regarding audio playback upgrade

### ISSUE THREAD

**Issue by Abdullah076** [quran/quran-ios#153]
1. option to select a range of verses to play
2. option to repeat the selected range
3. option to repeat individual ayat
4. option to set interval / break time between each verses while playing

**Comment by mohamede1945** [comment]
1. Good suggestion.
2. Good suggestion.
3. Duplicate for https://github.com/quran/quran-ios/issues/35
4. Good suggestion, but what scenarios could this be used for? I mean when people will use this feature?

Thank you so much for your requests! Jazak Allah Khyran!

**Comment by abunur** [comment]
regarding #4, we had produced some Quran CDs with a gap the length of the preceding Ayah, in order for the learner to be able to repeat after the reciter (as opposed to reciting same time, or manually having to pause the audio after each ayah).  However some folks found this annoying and wished it could be turned off (a luxury we do have in the software world).  Anyway, this might a use case for such a feature request.

**Comment by mohamede1945** [comment]
I see your point. 

@Abdullah076 Can you open 3 separate tickets for (1, 2, 4) because those can be done independently?

**Comment by Abdullah076** [comment]
here also agree with brother abunur. also some folks may recite with the reciter and alongside reading the arabic, they may wish to read the translation too. so option set a interval may be useful.
ok, opening.

**Comment by mohamede1945** [comment]
Closing it in favor of #155 #156 #157

**Comment by mohamede1945** [comment]
https://github.com/quran/quran-ios/pull/224 should implement the first three items.
