### ISSUE TITLE
Transliteration support

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [quran/quran-ios#166]
Add support for transliteration text is available here

https://github.com/GlobalQuran/data/blob/master/Transliteration/en.transliteration.txt

**Comment by Ashraf-Ali-aa** [comment]
@mohamede1945 I didn't realise that feature was available, also the link I have posted has better transliteration i.e in the app `Bismi Allahi arrahmani arraheem` text file `Bismillaahir Rahmaanir Raheem` the text file is more in line with the tajweed rules, any chance this could be updated with transliteration file. 

Jzk

**Comment by mohamede1945** [comment]
Just wondering what is the source of this data? Our translation data comes from http://tanzil.net/
cc @ahmedre

**Comment by ahmedre** [comment]
i think it's probably from tanzil.net - also, note that not all translations come from tanzil, a lot come from other sources as well (especially King Saud University in Saudi Arabia).

**Comment by Ashraf-Ali-aa** [comment]
the transliteration is from https://www.quran411.com/
