### ISSUE TITLE
Translation display issue

### ISSUE THREAD

**Issue by abunur** [quran/quran-ios#168]
Bug: noticed on iPad pro, prior to any translations being downloaded, if translation view is select a generic error pop up is displayed.  Was able to repeat several times before the screen to select / download translations was eventually displayed.

![img_1512](https://cloud.githubusercontent.com/assets/4803881/26537988/723512ee-4411-11e7-94ef-4a92a34d953a.PNG)

**Comment by mohamede1945** [comment]
That's actually a service error that I always notice too. @ahmedre do you encounter this? or do you have a log why the service fails?

**Comment by ahmedre** [comment]
we've had the webservice go down a few times due to load - what we do in Android is we keep a cached version of the file that we invalidate roughly once a week (and if it fails, we keep it longer until the service comes back up).

insha'Allah am hoping it doesn't go down again though.

**Comment by mohamede1945** [comment]
iOS also has a cache of it, but every time the user open the screen we reload the page and if it fails we show the cached list and also an error message.

**Comment by mohamede1945** [comment]
I don't think it is really a client issue. Please reopen if you disagree.
