### ISSUE TITLE
Search - reference the ayah

### ISSUE THREAD

**Issue by abunur** [quran/quran-ios#169]
When searching, the search results list should show the surah:ayah numbers to the side of each result

![img_1517](https://cloud.githubusercontent.com/assets/4803881/26538154/8b4d1d16-4412-11e7-8d64-08babd9089d4.JPG)

**Comment by mohamede1945** [comment]
That's actually the autocomplete results. You still need to tap the search button on the keyboard to see the results.

![screen shot 2017-05-29 at 10 36 32 am](https://cloud.githubusercontent.com/assets/5665498/26542576/bab16f24-445a-11e7-8597-218a49ecc891.png)

**Comment by abunur** [comment]
Ah it wasn't obvious that search needs to be tapped separately; I'd call that a UX issue in that case. Perhaps we need to execute search automatically when there is a pause in typing.

**Comment by mohamede1945** [comment]
Actually, this is how the app store search works.

Besides, if you are **really** searching for a word, you will eventually do either tap the search button on the keyboard or tap one of the autocomplete suggestions.

**Comment by mohamede1945** [comment]
On the other hand, the autocomplete suggestions I think should be improved a little bit. Currently, it shows the text till the end of the Ayah. Which makes the results differences are huge. One simple improvement would be to only show one or two more words.
