### ISSUE TITLE
Question about Highlighting Ayah when playing audio

### ISSUE THREAD

**Issue by sohaeb** [quran/quran-ios#176]
I always wondered how did all the quran apps manage to implement this feature (i.e: play the audio of the highlighted ayahs), I finally found the place to ask lol.

Would anyone be kind to explain how this works. like, does the app trim the audio or what exactly ?

Bonus if someone can link a file that actually implement this.

Jazak allahu khearn.

ps: Thank you so much for making this open source. I think it is really sad that islamic apps haven't reached this step where they open source their apps. There are so many advantages for making an open source.

**Comment by ahmedre** [comment]
see my answer on quran/quran_android#888 since it works the same way on iOS and Android.

**Comment by mohamede1945** [comment]
Thanks @ahmedre for your answer.
@sohaeb, hope Ahmed clarified it well, he is the best one to answer it as he was the one behind the idea for several years and iOS is just trying to port his great work.

**Comment by mohamede1945** [comment]
Please let us know if you need more help.
