### ISSUE TITLE
Simple Settings Screen

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#18]
Implement a simple settings for the download amount (Juz, Sura, Page).

**Comment by ahmedre** [comment]
for simplicity, consider not doing this - i like the Apple way of having less options and just choosing what makes sense for the users ourselves, so i'd say leave this out.

in an even more ideal world, we can batch download - ex if you play something from the 30th juz', we download the entire juz'. if you play something from a large sura, we just download that sura, etc.

**Comment by mohamede1945** [comment]
Yes, I totally agree with that. 

Your suggestion might be simplified with always downloading Juz whatever the sura length.
