### ISSUE TITLE
Swift 4 branch

### ISSUE THREAD

**Issue by abunur** [quran/quran-ios#190]
please create a Swift 4 branch from Master.  Purpose of the branch is to modify the code base to compile with no errors or warnings under Swift 4 & Xcode 9.  Branch should remain separate (can continually merge from production back into Swift 4 branch) until such time as Swift 4 is officially released.  This will make the project production ready for iOS 11 and also offer an alternative branch for developers who are working with beta releases of iOS 11 and Xcode 9 in the interim.

**Comment by mohamede1945** [comment]
Let me know when you want to start working on it, so I can label it `in progress`.

**Comment by abunur** [comment]
@mohamede1945 can you mark this in progress now.  JZK

**Comment by mohamede1945** [comment]
Fixed by #201
