### ISSUE TITLE
[IMPORTANT] Incorrect Text Madani In Words.db 

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#198]
![image png](https://user-images.githubusercontent.com/5665498/31319812-893cbf76-ac37-11e7-9b6f-f59337433da2.jpeg)

As reported by @ahmedre

**Comment by mohamede1945** [comment]
It appears to exist in other places also.
2:181
8:6
36:52
37:130

as per naveed.

**Comment by mohamede1945** [comment]
We have the following places where words.db have a problem.

| No. | Location        | Problem           | Proposed Fix  |
| --- | :-------------: |:------------------------|:-------------|
| 1 | 2:181 | We have 2 **بَعْدَمَا** at `word_position` 3 & 4 | Remove the second one by replacing `text_madani` at `word_position` 4 by an empty string|
| 2 | 2:271 | Wrong pause at `word_position` 6 | Set the correct pause  &nbsp;  ۖ  |
| 3 | 3:7  | Wrong pause at `word_position` 14  | Set the correct pause  &nbsp;  ۖ  |
| 4 | 3:20  | Wrong pause at `word_position` 27 | Set the correct pause  &nbsp;  ۗ  |
| 5 | 3:73  | Wrong pause at `word_position` 22 | Set the correct pause  &nbsp;  ۗ  |
| 6 | 8:6 | We have 2 **بَعْدَمَا** at `word_position` 4 & 5 | Remove the second one by replacing `text_madani` at `word_position` 5 by an empty string|
| 7 | 8:49  | Wrong pause at `word_position` 11 | Set the correct pause  &nbsp;  ۗ  |
| 8 | 8:52  | Wrong pause at `word_position` 15 | Set the correct pause  &nbsp;  ۗ  |
| 9 | 10:39  | Wrong pause at `word_position` 12 | Set the correct pause  &nbsp;  ۗ  |
| 10 | 12:111  | Wrong pause at `word_position` 8 | Set the correct pause  &nbsp;  ۗ  |
| 11  | 20:128 | Wrong pause at `word_position` 12 | Set the correct pause  &nbsp;  ۗ  |

**Comment by mohamede1945** [comment]
cc @ahmedre @naveed-ahmad

While implementing test case https://github.com/quran/quran-ios/commit/21d8245c098481145c66d6f4753ca06720a9c6be, I found the above issues. I have fixed them in the iOS 0c4757bb3e597c7af8b210099aa1afd1759dac87 and wanted you guys to know that.

**Comment by naveed-ahmad** [comment]
Thanks, @mohamede1945 added the issue on api repo to keep track of these issues.
