### ISSUE TITLE
Swift 4, Xcode 9 Support

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#199]

**Comment by abunur** [comment]
@mohamede1945 I'll try to get a pull request out on this, this week.  Sorry had been interviewing like crazy (four interview a day!)

**Comment by mohamede1945** [comment]
No problem. I'm already on it since yesterday and almost finished it, but forgot to create an issue to track that until 30 mins ago :). 

Thank you anyway, I feel how hard it is to do many interviews. Good luck
