### ISSUE TITLE
Implement Last Viewed Page Bookmark

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#20]
- [x] Implement a simple bookmark screen with only last viewed page.
- [x] The data should be always up to date with the last page viewed by the user.

Full functionality of the bookmarking shall be in V2.

**Comment by mmahalwy** [comment]
woot!

**Comment by mohamede1945** [comment]
It's funny that I already implemented it :D

**Comment by mohamede1945** [comment]
Implemented!
