### ISSUE TITLE
Mark newly downloaded translations as active

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#206]
Refer to Android implementation https://github.com/quran/quran_android/commit/c0bbcb5ec1ae792f64050d9b1d92e9a1759c9af2

**Comment by raheelahmad** [comment]
This is done already, right? At least from the sample app's point of view, seems like after a translation is downloaded, it can be immediately used.

(I would love to contribute on some starter tasks).

**Comment by mohamede1945** [comment]
No, this is not done yet, unfortunately. It's a great starter task if you would like to contribute.

**Comment by raheelahmad** [comment]
I am trying to understand this from a user perspective before delving into the code. 
Does "active" here mean that once downloaded, the new translation is selected here?

<img width="390" alt="Screenshot of Simulator (12-16-23, 2-22-57 PM)" src="https://github.com/quran/quran-ios/assets/54114/7cd4037e-d20c-4c9b-8279-ed54b01ef9ef">

**Comment by mohamede1945** [comment]
Yes, exactly. When a new translation is downloaded, it goes into the downloaded section, users have to tap on the translation to make it active and be able to see it in the Quran translation pages.
