### ISSUE TITLE
Have a similar app, how can I implement the overlaying reading function?

### ISSUE THREAD

**Issue by onurgenes** [quran/quran-ios#212]

**Comment by mohamede1945** [comment]
So what did you try so far?

In nutshell, we have a file for each Reciter that indicates the boundaries of the Verse in the audio file and we have a file for the Quran images that show us the areas each Verse occupies. Then when the reciter starts a new Verse we know from the first file which verse it is and use the areas from the second file to highlight the verse.

**Comment by onurgenes** [comment]
I'll check that out. I am not started implementing and could'n find any email address to reach out. When I start implementing, will let you know.

**Comment by mohamede1945** [comment]
Please let me know if you need more help.
