### ISSUE TITLE
SKStoreReviewController - asking for rating

### ISSUE THREAD

**Issue by bekzattt** [quran/quran-ios#214]
It would be nice to add SKStoreReviewController in order to increase number of people giving rating to the app.

I believe it would increase position in app store search for Quran apps. As a result more people would be able to use this ad free and so useful  app!

**Comment by mohamede1945** [comment]
That sounds like a great idea. Thank you for submitting it.

Do you have triggering events in mind?

**Comment by bekzattt** [comment]
For triggering: we could use adding favorites

**Comment by mohamede1945** [comment]
Those are very good ideas. Thank you.

The issue has been fixed.

**Comment by mohamede1945** [comment]
The build project issue is fixed. But the rating idea is not yet :)

**Comment by mumer92** [comment]
Hi @mohamede1945  
I would love to integrate SKReviewController as I have had experience in implementing in a project. I will open a pull request. Before that I would like to hear by you that is is the best way? When the app starts first time, then review controller should be shown or we can do like this, show review controller after 7 days when app starts?

I will implement accordingly and open a PR.

**Comment by mohamede1945** [comment]
@mumer92 Thank you so much for helping out and may Allah give you high rewards in Jannah inshaa'Allah.
 
I would say we should ask people to review if they are really using the app and enjoying it. So, to me, someone who opened the app like 10 times in the last 7 days is using it at least once per day.

So the requirement would be: we should show the rating view if the app is opened at least 10 times and the user used the app for at least 7 days.

What do you think?

**Comment by mohamede1945** [comment]
I would also add a persistent link in the settings screen to deep link into the app store for the user to review the app. But your Pull request doesn't need to include both of course.

**Comment by mumer92** [comment]
@mohamede1945 Yes this seems quite right. I will try to start to implement like you suggested.
