### ISSUE TITLE
Doesn't work on Xcode 9.1 with Swift 4.0.2

### ISSUE THREAD

**Issue by SafeenAzad** [quran/quran-ios#215]
Hi there, 

This app doesn't compile or run on Xcode 9.1 with Swift 4.0.2 

error message 
```
module compiled with Swift 4.0 cannot be imported in Swift 4.0.2: /path/to/project/quran-ios/QuranFoundation/QuranFoundation.framework/Modules/QuranFoundation.swiftmodule/x86_64.swiftmodule
```

**Comment by mohamede1945** [comment]
Thank you for reporting that. I will try to fix it today.

**Comment by SafeenAzad** [comment]
Have you worked on it bro?

**Comment by mohamede1945** [comment]
Sorry not yet.  I'm migrating all the work to a new computer.

**Comment by knail1** [comment]
I have the same problem gents, tried to run on Xcode9.2 with Swift 4.0.3

...../quran-ios/QuranFoundation/QuranFoundation.framework/Modules/QuranFoundation.swiftmodule/x86_64.swiftmodule

**Comment by KosratDAhmad** [comment]
I have the same problem with Xcode 9.2 with Swift 4.0.3

**Comment by mohamede1945** [comment]
I have fixed it in https://github.com/quran/quran-ios/pull/217 please reopen if it didn't work for you.

Sorry everyone for the inconvenience.

**Comment by knail1** [comment]
thanks for fixing bro. builds perfectly now.

**Comment by SafeenAzad** [comment]
Thank you.
