### ISSUE TITLE
Hadith app

### ISSUE THREAD

**Issue by abumusamq** [quran/quran-ios#219]
Assalamu alaykum wa rahmatullahi wa barakatuh

I'm the developer and maintainer of muflihun.com

I wrote Hadith app for iOS but because of circumstances I wasn't able to publish it to app store. I would like to give away the source code (written in Swift 2) so someone can possible port it to latest version of Swift (4) and publish it on AppStore for people to take benefit from it. 

It may be one of the on-going charity that will benefit each one of us in the hereafter.

Github repo: https://github.com/muflihun/Hadith
Repo contains screenshots for both app and today widget with icons and xcode project files and everything else needed.

Baraak Allahu feekum wa jazaakumullahu khayran

**Comment by abumusamq** [comment]
If someone actively start working on it please let me know for initial sqlite database files

**Comment by mohamede1945** [comment]
We alikom elsalam we rahmat Allah we barakatoh,

Thank you so much for doing that. May Allah accept from you and give you high rewards in the afterlife.

I will definitely try to convert the code and publish the app on the app store. It might take some time, but hopefully, we can do it as soon as possible.

You can e-mail us the SQLite DB if it is not open source to ios@quran.com.
Jazak Allah khyran and may Allah reward you highly for doing that.

**Comment by abumusamq** [comment]
walykumussalaam wa rahamatullahi wa barakatuh ya akhi,

I have sent you an email 

Wassalaam

**Comment by ahamedsaifudeen** [comment]
This looks exciting. @mohamede1945 Any updates on this?

**Comment by mohamede1945** [comment]
Unfortunately, I didn't spend any time working on this yet. But please feel free to start the work if you would like to.

**Comment by ahamedsaifudeen** [comment]
@mohamede1945 Sure, I am happy to start the work. I don't see the database file in the github. Can you share the hadeeth db file?

**Comment by ahmedre** [comment]
might work better under the leadership of https://github.com/sunnah-com/?

**Comment by mohamede1945** [comment]
@ahamedsaifudeen  I think it is better if you ask @abumusamq for the file and I agree with @ahmedre to work under sunnah.com.

**Comment by RafeeSoft** [comment]
I am happy to start the work. I don't see the database file in the github. Can you share the hadeeth db file to inforafeesoft@gmail.com

**Comment by faizankhananiss** [comment]
please share the database  to faizan.saleem.khanani@gmail.com

**Comment by mohamede1945** [comment]
Closing this as the app doesn't include adding hadith section.
