### ISSUE TITLE
Quran IOS Crash

### ISSUE THREAD

**Issue by abdelouali** [quran/quran-ios#22]
When I lauch the app, after it showing me a green header and a blank page it the app crashes. My IOS version is 8.1.2.

I'am now updating to 9.0.

Hopefully it wil work so

**Comment by mohamede1945** [comment]
Please don't update.

**Comment by mohamede1945** [comment]
I got the issue and I'm trying to resolve it now. But that would be great if you could help me test on iOS 8 device.

**Comment by abdelouali** [comment]
Allright, that was just on time hahaha. I aborted the Update.

**Comment by mohamede1945** [comment]
Thank you so much :)

**Comment by abdelouali** [comment]
Will the update or fix be posted to Hockeyapp?

**Comment by mohamede1945** [comment]
Yes, now with any new update, you will get a notification from hockeyapp to install the new build.

**Comment by abdelouali** [comment]
Allright, thank you.

**Comment by mohamede1945** [comment]
Fixed in v1.0.1
