### ISSUE TITLE
Explanation needed

### ISSUE THREAD

**Issue by ibrahimkteish** [quran/quran-ios#221]
https://github.com/quran/quran-ios/blob/69937f438f9bbdea602f8b761d670efa78a6b26c/VFoundation/Protected.swift#L60

Could you please elaborate more on why you are doing this here instead of:
`body(&_data)`
@mohamede1945

**Comment by mohamede1945** [comment]
Yeah, I think both should be fine. It was a copied from somewhere on the internet.

**Comment by ibrahimkteish** [comment]
Thank you :)
