### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by alisalsalem88** [quran/quran-ios#223]
public init<InteractorType: Interactor>(_ interactor: InteractorType)
        where InteractorType.Input ==Void, InteractorType.Output == Output {
            executeClosure = interactor.execute
    } 

Text clarification ::
Cannot assign value of type '(Void) -> Promise<Output>' to type '() -> Promise<Output>'

What is the solution and all thanks to you

**Comment by mohamede1945** [comment]
Which version of Xcode are you using?

**Comment by alisalsalem88** [comment]
Xcode 9

**Comment by mohamede1945** [comment]
Try using Xcode 9.2

**Comment by alisalsalem88** [comment]
updated Xcode 9.3
The same problem
Attachment Picture 
[https://i.imgur.com/A6nHWfY.png](url)

**Comment by mohamede1945** [comment]
That's extremely weird. I'm using Xcode 9.2 and I'm able to successfully build the project. I'm redownloading the project and try to see if I will be able to build it again.

**Comment by nayabraheel** [comment]
i am getting the same error in PromiseKit, my Xcode version is 9.3

**Comment by mohamede1945** [comment]
So you're compiling PromiseKit alone or within the app?

**Comment by nayabraheel** [comment]
Within the app, screenshot is attached.

![screenshot 2018-04-05 10 14 56](https://user-images.githubusercontent.com/4532751/38348264-36d6aee4-38ba-11e8-8d68-daf0e0d2112d.png)

**Comment by mohamede1945** [comment]
I see. But unfortunately, I don't know how I can solve these issues if I'm not able to face them (which is weird because I downloaded the code and compiled it). If you can fix the issue, PRs are welcome.

**Comment by pathegs** [comment]
I have the same problem using Xcode version is 9.3
I have an online Mac if you can check on this @mohamede1945 
If you can, I will the send you the login info

**Comment by mohamede1945** [comment]
Thanks @pathegs  for the suggestion. But I'm right now focusing on implementing [those features](https://github.com/quran/quran-ios/issues?q=is%3Aopen+is%3Aissue+label%3A%22Advanced+Audio+Player%22). 

It seems to be a simple compilation issue. Pull requests are very welcome.

**Comment by alisalsalem88** [comment]
I also have the same problem and what is the solution

**Comment by pathegs** [comment]
Please how to fix that compilation issue @mohamede1945 ?

**Comment by nayabraheel** [comment]
I tested it on Xcode 9.2 with swift 4.0 and its running now.

**Comment by mohamede1945** [comment]
Great to see you @nayabraheel  have it running 👍

**Comment by mohamede1945** [comment]
@pathegs I don't know how to fix it, sorry. Just google it and I think you will find many solutions.

**Comment by pathegs** [comment]
It works fine with Xcode 9.2 with swift 4.0

**Comment by mumer92** [comment]
Salaam, @mohamede1945 

I am reporting that this issue exists with the `Xcode 9.3` and `Swift 4.1`. My Xcode updated to 9.3 in background. When I tried to build this issue arises. 
I have cloned project locally and in progress to update. So far, I have successfully updated `PromiseKit` and PromiseKit is now on release build `6`. 
Now the issue is with framework`QuranFoundation.framework` as it was build with Swift `4.0.3` as reported by Xcode. 
I am available to update project, however you like.

**Comment by mohamede1945** [comment]
Thanks, @mumer92 for taking the time to do that. I will try to download Xcode 9.3 and build this framework and provide it as soon as possible.

**Comment by mohamede1945** [comment]
https://github.com/quran/quran-ios/pull/236 should resolve this issue

**Comment by mohamede1945** [comment]
Sorry for taking too long to resolve this, since I was very busy at work and implementing the playback functionality and I got sick last week the whole week.

**Comment by mumer92** [comment]
@mohamede1945 
May Allah bless you with good health. 

As I wrote before, `PromiseKit` is now at version `6`, [PromieKit migration](http://promisekit.org/news/2018/02/PromiseKit-6.0-Released/), I have updated it locally but it has code breaking api changes, what do you suggest, update pods in next version or should I open a PR? I have updated locally.

**Comment by mohamede1945** [comment]
@mumer92 Jazak Allah Khyran :)

If you have the changes for updating the PromiseKit pod. Feel free to open a PR.

**Comment by mumer92** [comment]
Seems like `DispatchQueue.default` has been removed. It has been referenced many time in project. Sometime it looks like in `global` queue or sometimes it looks like `main` queue. I think we should not update pod of `PromiseKit`. We can look it sometime after with thorough review.
