### ISSUE TITLE
Persistent App Rating Link in Settings

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#226]
This issue https://github.com/quran/quran-ios/issues/214 gives us a proactive way to ask the user to review the app. But here we would like to give a persistent way for the user to navigate to the app store to rate the app.

Users would expect to have an entry in the settings screen to navigate to the app store page to write a review about the app. Similar to how it is suggested [here at the end of the page](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview).

**Comment by mumer92** [comment]
In the Settings, the cell is created by the `Setting` struct, I wanted to ask if 

1) Should I add Image to cell as `audio` and `translation` cell has image, if yes, what image would you recommend.
2) What should be the text title text of rating cell and should I use google translate to generate translations of that keyword?
