### ISSUE TITLE
User Stuck in Detail Screens (Settings Detail Screen and translation detail screen)

### ISSUE THREAD

**Issue by dhgillani** [quran/quran-ios#241]
When user press in translation button from surah detail page it will be stuck in detail page.
As there is no back button.
Similarly in Settings detail pages.
Because you are using UIViewcontroller there.
Kindly change that to UINavigationController.

**Comment by mohamede1945** [comment]
Can you show screenshots where the user is stuck? Because I don't see it in the app at all. Also please tell me which iOS version are you using?

**Comment by mohamede1945** [comment]
The issue is open for too long without more information. Please reopen if needed.
