### ISSUE TITLE
'QuranFoundation' was built without full bitcode while doing archiving.

### ISSUE THREAD

**Issue by dhgillani** [quran/quran-ios#242]
Error in xcode:
'QuranFoundation' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file

**Comment by mohamede1945** [comment]
What are you trying to do?

**Comment by mohamede1945** [comment]
Are you trying to archive the app for app store submission?

**Comment by dhgillani** [comment]
Yes

**Comment by mohamede1945** [comment]
`QuranFoundation` is closed source, we did that to prevent people from downloading the code and uploading it as is to the app store. But you are more than welcome to use any part of the code in your project.
