### ISSUE TITLE
Getting error in SQLite.Swift file.

### ISSUE THREAD

**Issue by karthickkck315** [quran/quran-ios#244]
Hi All,
Am run this app in XCode 9.2 version. Am getting error's from SQLite.Swift file.
<img width="1440" alt="screen shot 2018-05-22 at 12 31 24 pm" src="https://user-images.githubusercontent.com/4092436/40346944-1264d488-5dbc-11e8-9edb-4aa7d50e55b8.png">

**Comment by mohamede1945** [comment]
Sorry for late reply. Try to use Xcode 9.3

**Comment by karthickkck315** [comment]
Thank you so much.
and then are you using quran page load using images ?? ,And then give me your personal mail id please

**Comment by mohamede1945** [comment]
Yes, we use images to render the Quran. My email is the same as my username @gmail.com.

**Comment by mohamede1945** [comment]
Please reopen if you need more help.
