### ISSUE TITLE
Surah Al-Fatiha not Downloading on IOS 8.1.2 

### ISSUE THREAD

**Issue by abdelouali** [quran/quran-ios#25]
Surah Al Fatiha does not completely download.
After downloaded about 80% of the surah the downloader don't do anthing. 

If seems the failure is only for Surah Al-Fatiha.

**Comment by mohamede1945** [comment]
Which reciter did you choose?

**Comment by abdelouali** [comment]
it only works properly with Abd Al-Basit (Gapless)
