### ISSUE TITLE
Cannot build with Xcode 10

### ISSUE THREAD

**Issue by aboualiaa** [quran/quran-ios#254]
The QuranFoundation.framework (Which is Compiled Using Swift 4.1) cannot be imported by the Swift 4.2 Compiler. Please create a beta for Xcode 10, or if possible provide source code for local compilation.

**Comment by mohamede1945** [comment]
Sure, I will try to get it as soon as possible inshaa'Allah

**Comment by mohamede1945** [comment]
After a rethink and I don't have Xcode beta installed yet. I think you can just try to use the latest stable version of Xcode 9.4.1 and it should work. When Xcode 10 will be released, we will add support for it. Sorry about that.

**Comment by aboualiaa** [comment]
Kind of defeats my purpose of testing the app on iOS 12, which is coming out soon anyway 😎.

**Comment by mohamede1945** [comment]
I really appreciate that I'm a little bit busy finalizing https://github.com/quran/quran-ios/milestone/5 as soon as I get that done will make this as my top priority.
