### ISSUE TITLE
Qaris list getting only 2 qaris

### ISSUE THREAD

**Issue by SayedObaid** [quran/quran-ios#314]
Al-Salam alaykom, I noticed that the github virsion gets only 2 qaris however the virsion on the app store contains a lot of qaris, is that an issue in the app’s data?

**Comment by mohamede1945** [comment]
We alikom elsalam, it is intentional.

**Comment by wajdi1987** [comment]
I have the same problem. why it is intentional? is this not an open source? and how could we add more reciter ?

**Comment by ahmedre** [comment]
It is open source. But unfortunately, many people have taken the code, added advertisements or made it a paid app and republished it with a different name (while still costing us money for the servers, bandwidth, etc), despite this being against the license.

As a way of making it slightly more difficult while still allowing people to contribute, we added 2 qaris only for the open source one.

If you have a sheikh you’d like to contribute to Quran for iOS (and Quran for Android), you can share the timing file and source files here and we’d be happy to add it in the next release.

**Comment by wajdi1987** [comment]
Is there a way to get the full version by donating or for an amount of money?.
