### ISSUE TITLE
Adding more reciters

### ISSUE THREAD

**Issue by wajdi1987** [quran/quran-ios#315]
Salam aleikom,
Thank you so much for this great source code, but I have one question, the android version has more than 2 reciters, is there a way to add more like in the android version please? because all I get is 2 reciters :(

**Comment by ahmedre** [comment]
Wa3laikum alsalam,
The app contains the same list as Quran for Android - please see #314 for why this limitation exists (in both open source repositories for the Android and iOS apps), but not in the released app on the app stores.
Walsalam 3alaikum.
