### ISSUE TITLE
Cannot build with Xcode 10.2

### ISSUE THREAD

**Issue by bertugyilmaz** [quran/quran-ios#317]
Hi, I cannot compile new swift 5 version QuranFoundation.framework. Can you help me this issue? I want to upgrade swift version, how can i this?

**Comment by mohamede1945** [comment]
Sorry, I don't think I will do it soon. Try using an older version of Xcode.

**Comment by shamzahasan** [comment]
@mohamede1945 buddy, I am using your Quran as a feature or you can say as a part of my app that you actually allowed, but now App Store is not accepting builds from older versions of Xcode, not even with 10.0. Please help us to grow and spread your beautiful efforts.

**Comment by mamnun** [comment]
is `QuranFoundation` source code available, I'd be happy to convert it into swift5

**Comment by mohamede1945** [comment]
Unfortunately, it is closed source.

**Comment by vevuethomas** [comment]
hi any luck for new update

**Comment by selim** [comment]
> Unfortunately, it is closed source.

I cannot build,, can you supply compiled version ?? 
i have error-> 
<unknown>:0: error: module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler: quran-ios/QuranFoundation/QuranFoundation.framework/Modules/QuranFoundation.swiftmodule/x86_64.swiftmodule

**Comment by sallyahmed** [comment]
@mohamede1945 is it paid source ? , please contact me `eng.sally.ahmed@gmail.com`

**Comment by mohamede1945** [comment]
It is not a paid source. You can compile the app using Xcode 10.1 with no issues.

**Comment by sallyahmed** [comment]
@mohamede1945  there is UI issue with iOS 13 :(

**Comment by mohamede1945** [comment]
You can do some objc runtime behavior to fix them.

**Comment by mohamede1945** [comment]
We have recently open sourced QuranEngine, please see the updated readme.
