### ISSUE TITLE
Getting compiler error in xcode 10

### ISSUE THREAD

**Issue by karthickkck315** [quran/quran-ios#319]
Hi,
 Am using older version Quran source. it's working in xcode 9.4.1 but in xcode 10 and above  getting below mention error in 
<unknown>:0: error: module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /Users/apple/Documents/6:8:18/Quran /QuranFoundation/QuranFoundation.framework/Modules/QuranFoundation.swiftmodule/x86_64.swiftmodule

can you please give me any suggestion.

**Comment by karthickkck315** [comment]
ya ok Please...

**Comment by mohamede1945** [comment]
I just checked and it is working just fine. Which Xcode version are you using?

**Comment by karthickkck315** [comment]
Amusing the old source code Swift version 4.0 am trying to convert 4.2 but am getting above issue.
Amusing Xcode 9.3,9.4.1 and migrate another one project and change many more file. But now am trying to run the latest version of Xcode 10 and above it's getting this type of issue. Can you please help me to the shootout this issue.

**Comment by karthickkck315** [comment]
Any updates?? And also please help me to remove the tab bar and use the navigation to quranviewcontroller??

**Comment by mohamede1945** [comment]
What is the feature you're working on, is this for our app?

**Comment by karthickkck315** [comment]
Yes, your app but we need required only quran slide and also we don't want tabbar instead we have to push to quran view directly from one view controller

**Comment by mohamede1945** [comment]
Sorry, I still don't understand why you want to change the current UI of the app? And why you can't use the latest version of the code.

**Comment by karthickkck315** [comment]
Ya am using latest source code only.
In old version am using below code to navigate my source code to your source code

```
 let chapterReading = Container().createSurasNavigationController()
self.navigationController?.present(chapterReading, animated: false, completion: nil)
```

but in latest source i can't navigate to my source to your source code.

**Comment by mohamede1945** [comment]
Sorry, we don't support other apps using this code. If you have issues, building the code in this repo let us know.
