### ISSUE TITLE
Title not visible in dark modes after IOS update

### ISSUE THREAD

**Issue by abdelouali** [quran/quran-ios#323]
After the last ios update the title is not visible anymore in dark modes. The title color needs to change to white after switching to dark modes. 

![DDCD7E1B-0F4E-4E13-880F-6DE64491A8E5](https://user-images.githubusercontent.com/13354388/65342039-27de3580-dbd2-11e9-9049-d78751e903e9.png)
![265ADCFD-721A-4AC0-906E-009067AD1E1F](https://user-images.githubusercontent.com/13354388/65342040-27de3580-dbd2-11e9-95bb-42c85c0567a2.png)
![1FD85097-EF29-4BA0-993F-DCD0C59790DB](https://user-images.githubusercontent.com/13354388/65342041-27de3580-dbd2-11e9-8a84-1714909feb05.png)

**Comment by mohamede1945** [comment]
Which iOS version are you using?

**Comment by abdelouali** [comment]
i checked today and the issue is fixed. I think it had something to do with IOS. I will close this issue.
