### ISSUE TITLE
xcode not archive app

### ISSUE THREAD

**Issue by ahmed-bassiouny** [quran/quran-ios#324]
bitcode bundle could not be generated because '/Users/admin/Workspace/Swift/quran-ios-master/QuranFoundation/QuranFoundation.framework/QuranFoundation' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/admin/Workspace/Swift/quran-ios-master/QuranFoundation/QuranFoundation.framework/QuranFoundation' for architecture arm64

**Comment by muisawe** [comment]
@mohamede1945  
I am also facing this problem, could you help us to move over it ?!

**Comment by mohamede1945** [comment]
We have recently open sourced QuranEngine, please see the updated readme.
