### ISSUE TITLE
Volume bar bug when connected to bluetooth headphone

### ISSUE THREAD

**Issue by abdelouali** [quran/quran-ios#329]
I found a bug. When playing Quran on my wireless headphones the volume bar of my Iphone. Shows up and keep on showing itself.

I made a small GIF to show the issue: https://imgur.com/a/c8SluE6
(the file was to big for Github)

**Comment by mohamede1945** [comment]
Is it an intermittent issue? Or a persistent one?

**Comment by abdelouali** [comment]
This is a persistent one

Op ma 13 apr. 2020 om 00:48 schreef Mohamed Afifi <notifications@github.com>

**Comment by mohamede1945** [comment]
Is it still reproducible? I don't see it reproducible on my iPhone.

**Comment by mohamede1945** [comment]
Please, reopen if you are able to reproduce.
