### ISSUE TITLE
Add mushaf with tajweed.

### ISSUE THREAD

**Issue by ravshansbox** [quran/quran-ios#332]
Ability to choose mushaf would be nice, especially great if there is at least one mushaf with tajweed.

**Comment by ravshansbox** [comment]
http://www.easyquran.com has ready to use high quality scanned pages.

**Comment by mohamede1945** [comment]
Good suggestion! Thanks for the reference

**Comment by mohamede1945** [comment]
Duplicate of #79

**Comment by ravshansbox** [comment]
I'm not sure this is duplicate, tajweed mushaf was only one example. Actually I was referring more to old and new Madinah mushafs.

**Comment by mohamede1945** [comment]
Oh, I see. These are also part of the plan as well inshaa'Allah. They are under [this label](https://github.com/quran/quran-ios/labels/Support%20Different%20Mushafs). Do you see something missing under that label?

**Comment by ravshansbox** [comment]
@mohamede1945 ough, sorry, I should have searched before opening. Yes, I see, there is already an open issue (#196) related to this. Jazakalloh!
