### ISSUE TITLE
Don't show any english word or number in mushaf mode

### ISSUE THREAD

**Issue by ravshansbox** [quran/quran-ios#333]
Currently it is showing juz, hizb, surah names, page number in english in muhsaf mode. It's undesirable, because it is preventing to feel like one is reading real mushaf. Better to show them all in arabic letters and numbers.

**Comment by mohamede1945** [comment]
You should be able to do that by choosing Arabic as a language for the app in the Settings app. Don't change the language of the iPhone, just the language of the Quran app. https://www.howtogeek.com/441716/how-to-change-the-language-of-an-app-on-your-iphone-or-ipad/
