### ISSUE TITLE
Question: Where are the locations of each word on a page stored? 

### ISSUE THREAD

**Issue by AbdullahM0hamed** [quran/quran-ios#339]
After checking all the databases I could find by searching [filename:.db](https://github.com/quran/quran-ios/search?q=filename%3A.db&type=) and checking all the resulting databases - I have been unable to determine the database that contains the location info for each word on a page. The closest appears to be [words.db](https://github.com/quran/quran-ios/blob/33d8b3f8fc4eb48cc9116b1115b893b8c23490c4/Quran/Resources/words.db), but it only has one column containing a single integer for the word_position of every word, and I don't know how that would help determine the co-ordinates of a word on a page.

Any information is appreciated, جزاكم الله خيرا

**Comment by ahmedre** [comment]
that's part of the [ayahinfo database](https://github.com/quran/quran-ios/blob/master/Quran/Resources/images/images_1280/databases/ayahinfo_1280.db)

**Comment by AbdullahM0hamed** [comment]
I did look at it before, but looking at it again, I realise that each `position` is a position for a word, which I didn't realise before, جزاك الله خيرا
