### ISSUE TITLE
Add a repeat ayah

### ISSUE THREAD

**Issue by madeny** [quran/quran-ios#342]
It would be nice if one could repeat ayah to memorize it.

**Comment by benomaire** [comment]
This is available, checkout the three dots at the corner of the screen. You can repeat ayah, or range of ayat.

**Comment by madeny** [comment]
> This is available, checkout the three dots at the corner of the screen. You can repeat ayah, or range of ayat.

Thank you @benomaire I didn't know it was there! I going to close this issue.
