### ISSUE TITLE
Swift 4.2.1 cannot be imported by the Swift 5.3.2 compiler: /Users/ibrahimsabry/Downloads/quran-ios-master/QuranFoundation/QuranFoundation.framework/Modules/QuranFoundation.swiftmodule/x86_64.swiftmodule

### ISSUE THREAD

**Issue by IosIbrahim** [quran/quran-ios#343]
Swift 4.2.1 cannot be imported by the Swift 5.3.2 compiler: /Users/ibrahimsabry/Downloads/quran-ios-master/QuranFoundation/QuranFoundation.framework/Modules/QuranFoundation.swiftmodule/x86_64.swiftmodule
could you update framework to swift 5 please

**Comment by selim** [comment]
Its been long time we couldnot get any response, is developer team still alive?

**Comment by nthrussell** [comment]
Please update the project to Swift 5, we want to contribute as well

**Comment by AbdallaIOS** [comment]
please update the code

**Comment by mohamede1945** [comment]
Please see updated readme. We have open sourced QuranEngine.
