### ISSUE TITLE
Quran Naskh for iOS

### ISSUE THREAD

**Issue by izBasit** [quran/quran-ios#347]
Can we have a Naskh version for iOS as well please. I was a user of the android version and loved it very much. 
Maybe we can have a similar app for iOS as well?

**Comment by ahmedre** [comment]
@mohamede1945 this is a good chance to add support for multiple page types (let's prefer that to multiple apps). was talking to @izBasit offline and he suggested we make a KMP project with all the page data - we can spearhead this and give it a shot to see how it works out.

**Comment by mohamede1945** [comment]
Yeah sure inshaa'Allah. I will start on this sometime after Ramadan inshaa'Allah.

**Comment by mohamede1945** [comment]
Duplicate of #148
