### ISSUE TITLE
QuranFoundation.framework/Modules/QuranFoundation.swiftmodule/x86_64.swiftmodule

### ISSUE THREAD

**Issue by maizer999** [quran/quran-ios#350]
I get the following error when install the pod file, clean the project and run 
<img width="641" alt="Screen Shot 2021-06-07 at 7 19 48 AM" src="https://user-images.githubusercontent.com/19888281/120958805-23b8c980-c761-11eb-9d69-f2bd3cc9ede2.png">

**Comment by fayzaElkadosey** [comment]
I am also facing this problem

**Comment by ahmedre** [comment]
please refer to the "Important Announcement" in the README - this project code is a snapshot from long ago and the new version is not open sourced. jazakumAllah khairan.
