### ISSUE TITLE
cant build in xcode 12

### ISSUE THREAD

**Issue by ilhamdoanggg** [quran/quran-ios#351]
i just wanna add indonesian language to this project but when i build always error and warning

![image](https://user-images.githubusercontent.com/9218660/122547350-30d79180-d05a-11eb-8a65-efee6c213e98.png)

thank you

**Comment by fayzaElkadosey** [comment]
I am also facing this problem

**Comment by ahmedre** [comment]
this is expected because this is a very old version of the code - please see "Important Announcement" section of the README on the main page.
