### ISSUE TITLE
Build Error [Building for iOS Simulator]

### ISSUE THREAD

**Issue by hamza72x** [quran/quran-ios#353]
Assalamu'alaykum

I am getting this error while building the project.

```
/Volumes/APFS/code/ios/quran.com.ios/Quran.xcodeproj Building for iOS Simulator, but the linked and embedded framework 'QuranFoundation.framework' was built for iOS + iOS Simulator.
```

![image](https://user-images.githubusercontent.com/48919542/139225290-9454573b-ed92-42ad-85b4-347e3eb9ae78.png)

Xcode Version `12.5.1 (12E507)`

**Comment by mohamede1945** [comment]
Please see updated readme. We have open sourced QuranEngine.
