### ISSUE TITLE
File urls are blocked

### ISSUE THREAD

**Issue by ravshansbox** [quran/quran-ios#354]
Recitation and translation file urls are blocked in some countries(at least in Uzbekistan). Please, ask reviewers (they are complaining and may decrease score averages) to install a vpn and try again if they can't download.

**Comment by mohamede1945** [comment]
Oh, it's like 99% of Uzbekistan reviews complaining about this issue. Thanks for pointing it out. I've replied to them all. However, do you know if there is a way to detect this, so the app can provide such information directly?

**Comment by ravshansbox** [comment]
It's quite tricky to detect them, because they are not timeouting the request, rather returning some invalid response. Attaching curl output to https://quranicaudio.com site.
![image](https://user-images.githubusercontent.com/1499188/147892610-ed1ef3cb-6f24-49c5-95d0-c91ef6ffa090.png)
How about spinning up a proxy-like (not an exact proxy, it's blocked as well) http server where you pass url you want to download and it serves it's content?

**Comment by mohamede1945** [comment]
I see. What about quran.com? is it not reachable as well?

**Comment by ravshansbox** [comment]
quran.com is reachable and also playing recitation without vpn. It’s audio files cdn looks like not blocked.

**Comment by mohamede1945** [comment]
@ahmedre Could you look at this please? It's probably affecting the Android app as well. Seems like the whole country is blocked, almost all reviews from Uzbekistan is complaining about this issue. Maybe we could do something with DNS to serve the audio and translation content from a quran.com url?

**Comment by ahmedre** [comment]
I spent a bunch of time on this a few months back, the problem is it's a cat and mouse game. see quran/quran_android#1210

**Comment by ravshansbox** [comment]
Just FYI, just changing DNS didn't solve the issue for me.

**Comment by mohamede1945** [comment]
@ahmedre From the conversation it seems you found a solution. Is it a client-side fix? Could you point me to the commit I don't see it linked there, please?

**Comment by ahmedre** [comment]
the fix worked temporarily for some time, but I am getting more reports again, so not sure it'll help or not, but I'll ping you the details.
