### ISSUE TITLE
Currently not able to return to page when we close

### ISSUE THREAD

**Issue by nmbaig** [quran/quran-ios#37]
we need to be able to return to same page so we can continue reading

it always starts on Surah Fatiha

**Comment by mohamede1945** [comment]
Thank you so much for filing this issue. I'll try to implement a hotfix for it and push it to the app store as soon as possible. If possible, do you have a steps to reproduce it.

**Comment by waseem01** [comment]
Steps:
Tap on Surah Baqarah -> Starts at Surah Fatiha
Swipe right to different verses 
Tap back
Tap on Surah Baqarah
Shows Surah Fatiha
State should be retained

**Comment by mohamede1945** [comment]
@waseem01 Sorry for late reply and happy Eid :)
I think it happens when the orientation change, correct?

**Comment by waseem01** [comment]
@mohamede1945 happy Eid to you and @all here
I should be able to dedicate more time soon inshAllah.
Nope, it happens in any orientation, play steps from my above description

![37](https://cloud.githubusercontent.com/assets/20160610/16716495/94fea03e-46c3-11e6-8dcf-e4bc98dad3fd.gif)

**Comment by mohamede1945** [comment]
@waseem01 Thanks so much for this gif, it makes it so so much easier to understand now. That's actually a different use case that's not implemented. Currently tapping on a Sura shows the first page of that sura or the page that is numbered with the label on the right of the row. For the users to go to the last visited page, he/she needs to go to Bookmarks section.

We can resolve this by adding a new row on Suras and Juz' tabs to at the top most for the last visited page. This way it's so easy for others to reach it. But I would like the input from other people (@ahmedre @mmahalwy) on this.

**Comment by ahmedre** [comment]
on Android, the behavior is the same as that video (and i don't think that should change imo - it would be strange if tapping sura Baqarah sometimes jumped to page 2 and other times jumped anywhere between pages 2 and 49).

on Quran, we have a "last read page" icon in the icon bar - tapping that returns you to the last page you were on.

![screenshot-2016-07-11_21 18 01 477](https://cloud.githubusercontent.com/assets/47771/16755090/c748fce8-47ad-11e6-9e58-11fbfae46833.png)

**Comment by mohamede1945** [comment]
The current description of the bug is invalid, tapping on a Surah name should go to the first page of that Surah, to return to last page (2 taps away) 1. Tap bookmarks 2. Tap the first item in the list. 

Also, we will implement in the future https://github.com/quran/quran-ios/issues/54 so that accidental tapping on a page doesn't overwrite the last page.
