### ISSUE TITLE
Control Arabic and Translation Font Size separtely

### ISSUE THREAD

**Issue by imthath-m** [quran/quran-ios#376]
The Translation view displays the verse in Arabic and translation in the selected language. As you can see below, the settings have a single option to control the font size. 

![image](https://user-images.githubusercontent.com/46041492/153752116-48ad710c-7651-46c0-8fd1-a493f7bbe680.png)

### Problem
Some languages look really big or small when compared to Arabic for the same font size. As you can see in the image above, the Tamil font looks massive for the same size. I would prefer to reduce the Tamil font by two points but keep Arabic the same size.

Also, the Font Size stepper shows an "A" near, which is completely unhelpful in this scenario as English is not the selected translation.

### Proposed Solution
Use two font size steppers to control the sizes of Arabic and the selected language separately. 

Optionally, show any letter or a word from Arabic and the Selected language near the steppers if possible. This is optional because the font updates in the background in real time, so the user can find the required size by looking at that full text.

**Comment by mohamede1945** [comment]
Jazak Allah khyran for reporting this! I totally agree.

**Comment by selim** [comment]
We have same problem in Turkish, I reported many times. Translation and Arabic font size must be separated like Tarteel app.
![IMG_36D86CA6AF38-1](https://user-images.githubusercontent.com/241385/156742646-04a215f5-656c-4d4c-87e6-9fb7864f4ce4.jpeg)

**Comment by mohamede1945** [comment]
Thank you! It's implemented and will roll out this week inshaa'Allah.

**Comment by imthath-m** [comment]
Wow! Jazak Allah Khair!

**Comment by mohamede1945** [comment]
This has been released few weeks back now.
