### ISSUE TITLE
Selecting verses

### ISSUE THREAD

**Issue by nmbaig** [quran/quran-ios#38]
not able to select verses for copy paste..

**Comment by mohamede1945** [comment]
Thank you so much for this feature request. It wasn't planned to be implemented in V2. But I think it makes sense and very useful for people. So, I will include it in V2 inshaa'Allah.

**Comment by hossamghareeb** [comment]
I will work on this feature

**Comment by mmahalwy** [comment]
woohoo! @hossamghareeb excited for you to help out :)

**Comment by mohamede1945** [comment]
Thank you so much! Jazaka Allah khyran :)

**Comment by waseemm** [comment]
@mohamede1945 I am an iOS developer & I'm available to contribute my free time in anyway I can.
 /cc @mmahalwy Danke for pointing me to the repo

**Comment by mohamede1945** [comment]
That's amazing, welcome @waseemm! Please have a look at [Contributions guilde](https://github.com/quran/quran-ios/wiki/Contributions) and let me know if you need more information.

**Comment by waseem01** [comment]
@mohamede1945 I had to move to personal github as zenhub wanted to peek into my organization :), my previous comment shall be deleted
