### ISSUE TITLE
QuranEngine Documentation/Sample App

### ISSUE THREAD

**Issue by basitjawaid** [quran/quran-ios#385]
Salam,
As older code is not supported now on, can we have some documentation or sample app which can help developers to understand the Quran Engine better ?
Any help will be appreciated in this regard.
Thanks

**Comment by mohamede1945** [comment]
Salam,

Unfortunately, there is no docs right now and I don't think I can write docs anytime soon. But feel free to read the code, tests and create docs to help yourself and others.

Thanks for raising the issue!

**Comment by mohamede1945** [comment]
There is a sample app created.
