### ISSUE TITLE
Can you add a group fully downloaded reciters (or marked as favorite) on top of list.

### ISSUE THREAD

**Issue by selim** [quran/quran-ios#386]
Can you add a group fully downloaded reciters (or marked as favorite) on top of list in "Select the reciter to listen to" page.

8<- Sample design for "Select the reciter to listen to" page -->8

Favorite Reciters

- Husary (Mujawwad, gapless)
- Husary (gapless)
- Minshawy Mujawwad

ENGLISH
- ...
- ...

ARABIC
- ...
- ...
----

Reciters can be mark as favorite in Settings->Audio Manager, for use in "Select the reciter to listen to" page.

__Originally posted by @selim in https://github.com/quran/quran-ios/issues/207#issuecomment-1073164066__

**Comment by mohamede1945** [comment]
Great suggestion! Thank you!

I think I can do something like "Downloaded Reciters" instead of "Favorite Reciters". Then I can show any partially or fully downloaded reciters in that section.

**Comment by selim** [comment]
when u planning to deploy? this feature not included in last two updates

**Comment by mohamede1945** [comment]
I'll try to implement it soon inshaa'Allah. Most probably the next or the one after update. Sorry, it may take sometime to implement.

**Comment by zukhan** [comment]
@selim sorry for the delay on this. Instead of "Downloaded Reciters", we're adding "Recent Reciters" for now. Take a look at this and let me know if this would help: https://github.com/quran/quran-ios/pull/399

**Comment by selim** [comment]
> @selim sorry for the delay on this. Instead of "Downloaded Reciters", we're adding "Recent Reciters" for now. Take a look at this and let me know if this would help: #399

"Recent Reciters" is ok, this would be helpful.

**Comment by mohamede1945** [comment]
@selim I'll try to release it by the end of the month inshaa'Allah. So sorry it took us too long.

**Comment by selim** [comment]
![image](https://user-images.githubusercontent.com/241385/216491916-0655875b-8642-4f0d-a84f-ecb4878acac4.jpeg)

Thank you brothers,
