### ISSUE TITLE
Crash when trying to share Ayah

### ISSUE THREAD

**Issue by faizmokhtar** [quran/quran-ios#387]
## Bug description
When I tap on the `Share...`  button to share ayah, the app will crash immediately. Happened on iOS 15.4 for iPad.

## Video recording
https://user-images.githubusercontent.com/1093100/161082044-d641f877-c221-40c9-8ecc-dabbd84b1a3b.MP4

I tried to find the related code in the QuranEngine but couldn't find any. Only found the translations for the string. Hopefully, this bug report is enough. If not maybe you can help give some pointers on where to look and I can try to contribute a PR for it.

**Comment by mohamede1945** [comment]
Hi,

Thanks a lot for the bug report. Which translation is this?

**Comment by faizmokhtar** [comment]
@mohamede1945 it's not related to the translation. The share button doesn't work on iPad. It will crash when I tap on it. Sorry for the misunderstanding.

![image](https://user-images.githubusercontent.com/1093100/161220844-6f1543be-5ed6-45aa-921f-688a8c7210bf.jpeg)

**Comment by mohamede1945** [comment]
Thanks for the explanation! I can reproduce it. I'll try to fix it today and send it for review.

**Comment by mohamede1945** [comment]
Fixed and released.
