### ISSUE TITLE
"Add Note" Option directs user to empty page

### ISSUE THREAD

**Issue by Exia-Narwhal** [quran/quran-ios#388]
****Issue description****

When an Ayah is held down to bring up the menu, and the "Add note" option is selected, the app opens an empty page that only contains a back button. The user must tap said back button to access the notes and highlights page.

This issue occured on an iPad Pro 10.5 inch running iOS 15.0.2

****Screen capture of the problem****

https://user-images.githubusercontent.com/102907768/161429419-673180ae-dcb7-40ea-8d2f-a14e20a9d1cd.mp4

_Footage sped up to reduce file size_

**Comment by mohamede1945** [comment]
Oh, I can reproduce it. Thanks for reporting it.

**Comment by mohamede1945** [comment]
I'll try to fix it today and send it for App store review.

**Comment by Exia-Narwhal** [comment]
جزاك الله خير!

**Comment by mohamede1945** [comment]
Fixed and released.
