### ISSUE TITLE
Husayri (Muhawwad, gapless) sync problem

### ISSUE THREAD

**Issue by selim** [quran/quran-ios#391]
- goto hud ayah 56 (11:56)
- select ayah and play
- app playing previous ayah while focusing current ayah

this case just for Husayri (mujawwad, gapless)

**Comment by mohamede1945** [comment]
Thanks a lot for reporting this! I can reproduce it.

@ahmedre this seems to be 2 problems with the audio:
1) Hud ayah 23: it says (صدق الله العظيم)
2) It then moves to ayah 24 reciting verse 23. Then the recitation is always shifted by 1 verse until the end of the surah.

**Comment by ahmedre** [comment]
jazakumAllah khairan, should be fixed now - got the report and fix from a brother working on another app earlier but didn't get a chance to upload until now.
