### ISSUE TITLE
How do I resolve dependency with this repo?

### ISSUE THREAD

**Issue by iamraafay** [quran/quran-ios#404]
I'm currently trying to resolve this repo as a dependency to my project via SPM. Xcode is stuck looking up for the reference.

**Comment by iamraafay** [comment]
Interestingly enough, the issue number is 404. 😂

**Comment by mohamede1945** [comment]
😂

How are you referencing it? Most probably you're using a tag and I haven't added a tag for a while now. I'd recommend you use a commit or the main branch. For example here is how we are using it in our App:
```
.package(name: "QuranEngine", url: "https://github.com/quran/quran-ios", .branch("main")),
```

**Comment by iamraafay** [comment]
👋🏽

I can resolve dependency with the repo based on what you have suggested. Do we have a doc or a guide on how to use it for the features I've listed in my query?

**Comment by mohamede1945** [comment]
Could you please revert the edit you made to the issue and instead open a new issue for the other inquiry? We would appreciate you doing this since it will allow others search for a similar problem and see the solution.

Thanks!

**Comment by iamraafay** [comment]
Created another issue regarding usage [here](https://github.com/quran/quran-ios/issues/405)
