### ISSUE TITLE
How to use QuranEngine?

### ISSUE THREAD

**Issue by iamraafay** [quran/quran-ios#405]
Hello Everyone,

I'm considering building an app to plan my prayers for the next day. It would remind me before I go to bed to pick surahs or a range of ayats for each farad prayer for the following day.

It's a convenient app for folks who know the Quran in a wide range but may not be able to reach their potential since they have no records of knowing how much Quran they already know. It can also be great for somebody who likes to learn the Quran to enrich their salah on an ongoing basis by reciting long surah, etc.

With that in mind, I've already started building out the solution, but now looking for ways to interact with the QuranEngine.

1) I'd like the user to be able to search surah by name and number.
2) I'd like the user to be able to search ayah by number along with surah.
3) Then present to them the page where the surah is starting or the first ayah in the range—allowing them to read through and prepare themselves for the prayer.
4) Once the selection is made, I take the user back to the core app I'm building.

Please help me get started with the QuranEngine to search and present the pages. I appreciate your help in advance.

**Comment by mohamede1945** [comment]
Unfortunately the engine lacks documentation and we welcome contribution.

As for your request, take a look at CompositeSearcher it contains the search code we use in the Quran app. For example, NumberSearcher and SuraSearcher might satisfy requirements #1 & #2.

Hope this helps.
