### ISSUE TITLE
Compilation error building for MacOS!

### ISSUE THREAD

**Issue by amirian** [quran/quran-ios#417]
This code wouldn't compile in the latest xcode version, several build errors as below:
AnyPublisher is only available in mac 10.15 or newer
PassthroughSubject is only available in mac 10.15 or newer
erasetoAnyPublisher() is only available in mac 10.15 or newer
map is only available in mac 10.15 or newer

**Comment by mohamede1945** [comment]
Thanks for reporting this. The library doesn't Mac OS, just iOS (see https://github.com/quran/quran-ios/blob/main/Package.swift#L9).

If you would like to add support for Mac OS, that would be great.

**Comment by amirian** [comment]
No, I just decided to make some extensions on iOS, but I wonder you have made all the parts private except the engine! That was public in past.

**Comment by mohamede1945** [comment]
Yeah, that was a decision to allow other people interested in creating their own Quran app to not have to worry about the business logic and can reuse an existing engine for that and build their UI and other features on top of the engine.

**Comment by mohamede1945** [comment]
I'm going to close the issue given that we are not going to support Mac OS.
