### ISSUE TITLE
update to swift 3

### ISSUE THREAD

**Issue by atefa2009** [quran/quran-ios#44]
The app is not work with  xcode 8 , need to convert swift 3

**Comment by mohamede1945** [comment]
Unfortunately, I'm a little bit busy nowadays. I should be back working on the project beginning of November inshaa'Allah.

**Comment by atefa2009** [comment]
inshaa'Allah man

**Comment by ahmedre** [comment]
i got this mostly working in #45 - still a few issues to iron out before it is mergeable though
