### ISSUE TITLE
Vietnamese UI Translation 

### ISSUE THREAD

**Issue by techyescountry** [quran/quran-ios#456]
Assalamualaykum, 
If I want to translate the app UI, do i just clone one language in localization/resources folder, translate and send a pull request? Thank you

**Comment by mohamede1945** [comment]
We alikom elsalam we rahmat Allah we baraktoh,

We very much appreciate such an effort.

Yes you can clone and add a new folder for the Vietnamese language. Basically you can translate this file https://github.com/quran/quran-ios/blob/main/Sources/Localization/Resources/en.lproj/Localizable.strings. The other files are automatically imported from the Android repo, so if you translate them there, I'll make sure to sync before next release inshaa'Allah.

**Comment by ahmedre** [comment]
Related to quran/quran_android#2284

**Comment by techyescountry** [comment]
@mohamede1945 I have also finished the Android translation, would be great if you can imported them from the Android repo.

**Comment by techyescountry** [comment]
Assalamualaykum, may i know roughly when will we have the next release?

**Comment by mohamede1945** [comment]
I'll try to test this later today inshaa'Allah and let you know. 

As for the next release schedule. It may take sometime (maybe 2 months) as I have been doing some refactoring and would like to complete it and take enough time to test the changes before releasing it.

**Comment by techyescountry** [comment]
I see. Ok inshaallah. Pls update me if the translation works fine with the ui layout.

**Comment by mohamede1945** [comment]
One additional question if you don't mind, the name of the app in English is "Quran". Would that work in Vietnamese or do we need to change it?

**Comment by techyescountry** [comment]
> One additional question if you don't mind, the name of the app in English is "Quran". Would that work in Vietnamese or do we need to change it?


"Kinh Quran" would be better for the app. But on Appstore listing i think putting the title as "Kinh Quran - Cô ran" as Quran is pronounced as Cô ran in vietnamese

**Comment by techyescountry** [comment]
> Apparently there are some changes in the Android repo that made my script that transforms android localization to iOS localization fail. I'll not be able to import them now. I'll try to do that before the release because I wanna fix the script once in case it breaks again.
> 
> For the time being here is a screenshot of the Settings app using only the localization you provided for iOS.
> 
> ![image](https://user-images.githubusercontent.com/5665498/241084770-146abdc8-f08f-4055-94ca-c9d2d841ec57.png)

MashaAllah, that's looks great. Maybe i'll copy the other xml files from en folder and translate it so you wont have troubles importing from the android project.

**Comment by mohamede1945** [comment]
> Maybe i'll copy the other xml files from en folder and translate it so you wont have troubles importing from the android project.

Appreciate your offer for help. But I have to fix the script this will help me with other languages as well and ensuring consistency across both apps. So, I don't want you to spend time on something that I'll have to fix anyway.

**Comment by techyescountry** [comment]
> > Maybe i'll copy the other xml files from en folder and translate it so you wont have troubles importing from the android project.
> 
> Appreciate your offer for help. But I have to fix the script this will help me with other languages as well and ensuring consistency across both apps. So, I don't want you to spend time on something that I'll have to fix anyway.

Ok brother, take care. Jazakallah Khairan.

**Comment by mohamede1945** [comment]
You are the one to be thanked. I appreciate your contribution a lot. May Allah reward you immensely

**Comment by mohamede1945** [comment]
Thank you brother @techyescountry! The new translation has been released for over a month now I believe.
