### ISSUE TITLE
Bookmarks error Iphone SE

### ISSUE THREAD

**Issue by abdelouali** [quran/quran-ios#46]
Salam,

i was reading the Customer  Reviews in the App store. A user has an error on bookmarking on his Iphone SE. 

Below a screenshot
![knipsel](https://cloud.githubusercontent.com/assets/13354388/19748088/f4395168-9bdf-11e6-9ed3-763ff247d258.PNG)

**Comment by ahmedre** [comment]
we haven't implemented bookmarking yet on the iOS app - it only saves the last page you were on right now.

**Comment by ahmedre** [comment]
closing in favor of #36
