### ISSUE TITLE
App force closed while reading sur or juz

### ISSUE THREAD

**Issue by abikh** [quran/quran-ios#598]
Hi
I am getting following error when i click on sura or juzh
 [QuranImageFeature] Images: Use bundle For reading hafs_1440 
QuranImageFeature/ContentImageBuilder.swift:63: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by abikh** [comment]
Open source version. I downloaded from here (github) and tried to run on xcode

**Comment by mohamede1945** [comment]
Thanks found the problem. Here is the fix: https://github.com/quran/quran-ios/pull/602

**Comment by abikh** [comment]
Thanks! Issue is fixed now
