### ISSUE TITLE
Reading & Listening Screen

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#6]
For the reading screen, we need to do the following:

- [x] Show a page from Quran.
- [x] User can switch to full screen (reading mode).
- [x] User can navigate to next and previous pages if applicable.
- [x] User can choose one of the available readers to listen to.
- [x] User can start listening to the current Qari.
- [x] User can pause the audio.
- [x] User can resume the audio.
- [x] User can fast forward the audio to the next Ayah.
- [x] User can go backward the audio to the previous Ayah.
- [x] User can stop the audio and return back to the readers selection.
- [ ] ~~User can choose the ability to repeat surahs (no repeats, 1, 2, 3 or infinite repeats).~~
- [x] If audio is playing, open next page when the current page is done
- [x] If audio is playing, automatically start next Surah when the current one is completed unless it's the last Surah.
- [x] Set the default download type to be by Juz.
- [x] While audio playing, needs to handle headphones command pause/play/stop.
- [x] When the audio is interrupted by external audio/music. The app should pause the currently playing audio.

**Comment by abdelouali** [comment]
Have you already created this one?  **Show a page from Quran.**
@mohamede1945

**Comment by mohamede1945** [comment]
This one is actually in progress.

**Comment by abdelouali** [comment]
Can you tell me what i can do? @mohamede1945

**Comment by mohamede1945** [comment]
You can design classes for Audio download and playback, then create PR with the designed classes, then we both can work on implementation.

**Comment by abdelouali** [comment]
Sounds good, Where do i need to put this classes in the main folder?

**Comment by mohamede1945** [comment]
Just follow the existing design, please.

**Comment by abdelouali** [comment]
Alright,

I will give it a try. Speak soon.


Op zondag 1 mei 2016 heeft Mohamed Afifi <notifications@github.com> het
volgende geschreven:

**Comment by mohamede1945** [comment]
Good luck! 👍

**Comment by abdelouali** [comment]
Shokran

Op zondag 1 mei 2016 heeft Mohamed Afifi <notifications@github.com> het
volgende geschreven:

**Comment by mohamede1945** [comment]
Hello,

Are you done with the design of audio classes? Because I'm almost done with the reading screen. So, I'd like to start working on Audio features.

**Comment by mohamede1945** [comment]
I've finished the reading screen. Now, I should start working on audio. So, I'll be waiting for an answer for 3 hours after that I'll start working on audio, sorry for that, V1 should be released in 18 days.

**Comment by abdelouali** [comment]
Unfortunately, there is something wrong with my macbook, and I brought him in. I think the OS crashes at startup. I got him back at the earliest Monday :(

**Comment by abdelouali** [comment]
I apologize for the late reply. I was at work

**Comment by mohamede1945** [comment]
Thank you for your kind reply. No worries at all! I'll start working on Audio features. You can start working on V2 features if you want. It will be mainly mimic other features the android has that we didn't implement in V1 like Bookmarking, Settings, etc.

**Comment by abdelouali** [comment]
Starting Monday I will hopefully be able to resume work. Can I test the V1 as it is launched.

**Comment by mohamede1945** [comment]
Definitely, I'll send you the app for internal testing. Thank you so much for offering the help and Jazak Allah khyran :)

**Comment by abdelouali** [comment]
Jazak Allah kyran, Insha'Allah.

**Comment by mohamede1945** [comment]
Feature implemented! Except repeat functionality will be moved to V2 since it's time-consuming and the current implementation is buggy.
