### ISSUE TITLE
Crash for Updating Last page from Last Pages Bookmarks

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#61]
After applying https://github.com/quran/quran-ios/pull/60 now there is a crash when the user opens the Quran from one of the last pages.

Steps to reproduce:
1. Assume you have in the "last pages bookmarks", pages 1 and 2.
2. Open the Quran from page 1.
3. Then swipe the page to go to page 2. The app will crash at this point.

I think the crash in function 
```swift
func update(page: LastPage, toPage newPage: Int) throws -> LastPage
```

**Comment by ahmedre** [comment]
i saw this crash before merging #62, but now i can't repro anymore.
tried also checking the value of `connection.run(update)`, and it seems to be correct when i run it.

can we close this?

**Comment by mohamede1945** [comment]
Yes, it doesn't crash, but it still throws a swift error. The problem is that if there are 2 records in the database with pages (3 and 4) then when the query is to update the record for page 4 to set it to page 3, the SQLite will throw an exception. I will try to fix it.

**Comment by ahmedre** [comment]
couple of ideas:
1. delete the page you're about to add first
2. query for both pages instead of just one, and if count is 2, then call update on the specific one

**Comment by mohamede1945** [comment]
I already fixed it here https://github.com/quran/quran-ios/pull/63 I also made the app crashes on debug build if there is a swift error.

**Comment by ahmedre** [comment]
awesome, jazakAllah khairan!

**Comment by mohamede1945** [comment]
You thank you so much! rabena yekremek :)
