### ISSUE TITLE
Issue with ‘Container’ class and Missing arguments for parameters 'downloader', 'remoteResources

### ISSUE THREAD

**Issue by looktaking** [quran/quran-ios#624]
Assalamu Alaikum,

May Allah bless everyone who works on this project for the noble efforts in creating this app.

I recently cloned the Quran iOS project and tried to run the example, but I came across a few issues.

The Container class does not conform to the AppDependencies protocol. It seems like the Container class is missing the following properties required by the AppDependencies protocol:

quranUthmaniV2Database
logsDirectory
databasesDirectory
remoteResources

I tried to provide default values for these properties, but I’m not sure if that’s the correct approach. Could you please provide some guidance on how to properly implement these properties in the Container class?

```code
    var quranUthmaniV2Database: URL { return URL(string: "https://")! }
    var logsDirectory: URL { return URL(string: "https://")! }
    var databasesDirectory: URL { return URL(string: "https://")! }
    var remoteResources: ReadingRemoteResources? { return nil }
```
 
![image](https://github.com/quran/quran-ios/assets/121838099/cb8f935e-ee42-4a2f-b3c1-a3b67c9c4c26)

**Comment by mohamede1945** [comment]
We alikom elsalam,

the latest commit passed CI: https://github.com/quran/quran-ios/commits/main/. I think you may be using the xcode project and not the workspace.

Please take a look at the [CI command](https://github.com/quran/quran-ios/blob/main/.github/workflows/ci.yml#L36), we are doing `xcrun xcodebuild build -workspace Example/QuranEngineApp.xcworkspace -scheme QuranEngineApp`. You need to open `QuranEngineApp.xcworkspace`.

**Comment by looktaking** [comment]
Thank you for your guidance, using `QuranEngineApp.xcworkspace` instead of the Xcode project, solved my issues.

I appreciate your prompt and helpful response.
