### ISSUE TITLE
Tafseer view has wrong text direction when app language is Arabic

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [quran/quran-ios#660]
This is the English view, properly formatted tafseer view:

![image](https://github.com/user-attachments/assets/d5f74680-2966-445e-8d32-1ba38904dc89)

This is the Arabic view, with incorrect LTR direction:

![image](https://github.com/user-attachments/assets/7fccbd63-1371-4796-b11b-b6792d41feae)

**Comment by mohamede1945** [comment]
Thanks a lot for reporting the issue. I'll make sure to fix it in the next release this week.

**Comment by mohamede1945** [comment]
This has been released today. Please update the app from the app store.

**Comment by MahmoudAlyuDeen** [comment]
Thank you for the super fast fix and follow up! I just tried the update and issue is resolved. ✅

This app remains the best way for me to read and listen to Quran, native UI and attention to detail. Thanks for the efforts.

❓ not sure where to place the English ayat numbers in the tafseer and notes views:

- this issue?
- a separate issue?
- no-op, as expected behavior?

![image](https://github.com/user-attachments/assets/3c3677ea-12da-4483-a725-9b4b4f330b39)

![image](https://github.com/user-attachments/assets/10784957-23de-4c33-9613-47cce2f291cb)

**Comment by mohamede1945** [comment]
Thank you for the kind words!

Please create a separate issue.
