### ISSUE TITLE
Tafseer view and notes view has English numbers for Ayat despite app language being Arabic

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [quran/quran-ios#666]
| Tafseer | Notes  |
|--------|--------|
| <img src="https://github.com/user-attachments/assets/0cfd3d6a-ca02-4923-b067-4a64d75418ee"> | <img src="https://github.com/user-attachments/assets/6fff96ac-3400-485d-b67c-daf1085e5563"> |

**Comment by mohamede1945** [comment]
I tried to repro #666 but I couldn't. I hope Youssef's PR has fixed it. Do you mind if you can test it in the example app?

**Comment by MahmoudAlyuDeen** [comment]
Sure I can try it. Thanks for the follow up.

❓ Is there an ipa or do I need to build it?

**Comment by mohamede1945** [comment]
Usually you need to build, but I've sent a new release for review. So, hopefully later today you can download it and verify.

**Comment by mohamede1945** [comment]
The new version is on the app store. Can you try it please?

**Comment by MahmoudAlyuDeen** [comment]
Fixed 🚀

![image](https://github.com/user-attachments/assets/a2d40c66-2557-4d85-8197-2e6574cc2510)

![image](https://github.com/user-attachments/assets/b5f665ef-f908-4deb-a34b-b88b0871bc00)

**Comment by mohamede1945** [comment]
Thanks @MahmoudAlyuDeen for verifying and thank you @yismailuofa for the fix.
