### ISSUE TITLE
Adding New Qari

### ISSUE THREAD

**Issue by farazhaider88** [quran/quran-ios#72]
Is there any way i can add new qari in application. what are steps to do this?

**Comment by mohamede1945** [comment]
I cannot remember the exact steps right now. Which type of Qari do you have gapless (i.e. each Surah is on its own audio file) or gapped (i.e. each Ayah is on its own audio file)?

There is a complication for the gapless audio that you need to have a database file that marks the start of each Ayah.

**Comment by farazhaider88** [comment]
Gapless
On Jan 22, 2017 4:06 PM, Mohamed Afifi <notifications@github.com> wrote:I cannot remember the exact steps right now. Which type of Qari do you have gapless (i.e. each Surah is on its own audio file) or gapped (i.e. each Ayah is on its own audio file)?
There is a complication for the gapless audio that you need to have a database file that marks the start of each Ayah.

**Comment by mohamede1945** [comment]
You can send to me the files, I'll try to add them.

**Comment by ahmedre** [comment]
let's try to remain consistent between iOS and Android

**Comment by mohamede1945** [comment]
That makes sense. Let's wait for @farazhaider88 to give us the files and then we all can see if we can add it or not and if yes we can add it to both iOS and Android.

**Comment by farazhaider88** [comment]
can you send me email address where i need to send you data?

**Comment by ahmedre** [comment]
@farazhaider88 which qari is it? do you have a link somewhere online where we can get their recitations (or is this only something you have?)

when you say "files" - do you also mean that you have a gapless database? jazakAllah khairan.

**Comment by mohamede1945** [comment]
Closing the issue, since there is no reply for 2 months. 

Feel free to re-open it again if you have answers to what Ahmed said.
