### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#8]
- [x] Home page will display the Quran table of content.
- [x] There will be 2 tabs (Surahs and Juz).

Surahs tab:
- [x] Surahs tab will list the surahs in an ascending order with the Juz as label.
- [x] Surahs will be numbered according to its order.
- [x] Surahs will show the the start page number.
- [x] Below the Surah name show whether it's (Makki or Madani) and number of verses.

Juz tab:
- [x] Juz tab shall show the Juzs in an ascending number in a sectioned manner.
- [x]  Each section will have 8 Quarters or (Roba).
- [x]  Each Quarter will show the first few words of the start Ayah.
- [x]  Each Quarter will show the name of the Surah it's in, the Ayah number and the page number.
- [x]  Each Quarter will show the Hezb number inside a pie on the left.

**Comment by abdelouali** [comment]
I would like to join you build this app and also translate it to Dutch

**Comment by mohamede1945** [comment]
That's great. I'll reply to your e-mail shortly.

**Comment by mohamede1945** [comment]
Implemented and committed to master.
