### ISSUE TITLE
Reduce app size to below 100mb

### ISSUE THREAD

**Issue by jayhub** [quran/quran-ios#86]
I know the size of the app has been reduced recently but its not enough. Need to find out what else can be done to reduce file size. Have you considered changing images from png to any other format? or is that not an option? I know it would be difficult but if we can keep it below 100mb on appstore that would be a great achievement. Unless people download the app via wifi, I think most cellular if not all do not let you download app that is more than 100mb.

**Comment by mohamede1945** [comment]
The current app size is already below the 100MB. You can download it with cellular internet.

**Comment by jayhub** [comment]
It shows on appstore as 106mb. But if its already below 100mb thats great.

**Comment by mohamede1945** [comment]
That's the installation size after uncompressing the IPA, not the download size. The download size is below 100MB.

I'm closing this issue since it's invalid.

**Comment by jayhub** [comment]
Oh right. I didn't think about that.
